apiVersion: apps/v1
kind: Deployment
metadata:
  name: say-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: say
  template:
    metadata:
      labels:
        app: say
    spec:
      containers:
      - name: say
        image:  gcr.io/text-to-speech-338303/say
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: say-service
spec:
  selector:
    app: say
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
